# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BVSTVP_cpp <- function(y, x, niter, nburn, nthin, c0, g0, G0, tau2, s0, S0, display_progress, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, starting_vals) {
    .Call(`_BVSTVP_BVSTVP_cpp`, y, x, niter, nburn, nthin, c0, g0, G0, tau2, s0, S0, display_progress, sv, Bsigma_sv, a0_sv, b0_sv, bmu, Bmu, starting_vals)
}

